# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sensors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/sensors.proto\x12\x03iot\"G\n\x0b\x41\x63\x63\x65lSample\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\r\x12\n\n\x02\x61x\x18\x02 \x01(\x02\x12\n\n\x02\x61y\x18\x03 \x01(\x02\x12\n\n\x02\x61z\x18\x04 \x01(\x02\"7\n\nTempSample\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\r\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\"r\n\x0eSensorEnvelope\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12!\n\x05\x61\x63\x63\x65l\x18\x02 \x01(\x0b\x32\x10.iot.AccelSampleH\x00\x12\x1f\n\x04temp\x18\x03 \x01(\x0b\x32\x0f.iot.TempSampleH\x00\x42\t\n\x07payloadb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sensors_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCELSAMPLE._serialized_start=28
  _ACCELSAMPLE._serialized_end=99
  _TEMPSAMPLE._serialized_start=101
  _TEMPSAMPLE._serialized_end=156
  _SENSORENVELOPE._serialized_start=158
  _SENSORENVELOPE._serialized_end=272
# @@protoc_insertion_point(module_scope)
