/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_IOT_PROTO_SENSORS_PB_H_INCLUDED
#define PB_IOT_PROTO_SENSORS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _iot_AccelSample {
    uint32_t timestamp_ms;
    float ax;
    float ay;
    float az;
} iot_AccelSample;

typedef struct _iot_TempSample {
    uint32_t timestamp_ms;
    float temperature;
} iot_TempSample;

typedef struct _iot_SensorEnvelope {
    pb_callback_t source_id;
    pb_size_t which_payload;
    union {
        iot_AccelSample accel;
        iot_TempSample temp;
    } payload;
} iot_SensorEnvelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define iot_AccelSample_init_default             {0, 0, 0, 0}
#define iot_TempSample_init_default              {0, 0}
#define iot_SensorEnvelope_init_default          {{{NULL}, NULL}, 0, {iot_AccelSample_init_default}}
#define iot_AccelSample_init_zero                {0, 0, 0, 0}
#define iot_TempSample_init_zero                 {0, 0}
#define iot_SensorEnvelope_init_zero             {{{NULL}, NULL}, 0, {iot_AccelSample_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define iot_AccelSample_timestamp_ms_tag         1
#define iot_AccelSample_ax_tag                   2
#define iot_AccelSample_ay_tag                   3
#define iot_AccelSample_az_tag                   4
#define iot_TempSample_timestamp_ms_tag          1
#define iot_TempSample_temperature_tag           2
#define iot_SensorEnvelope_source_id_tag         1
#define iot_SensorEnvelope_accel_tag             2
#define iot_SensorEnvelope_temp_tag              3

/* Struct field encoding specification for nanopb */
#define iot_AccelSample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    ax,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    ay,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    az,                4)
#define iot_AccelSample_CALLBACK NULL
#define iot_AccelSample_DEFAULT NULL

#define iot_TempSample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2)
#define iot_TempSample_CALLBACK NULL
#define iot_TempSample_DEFAULT NULL

#define iot_SensorEnvelope_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   source_id,         1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,accel,payload.accel),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,temp,payload.temp),   3)
#define iot_SensorEnvelope_CALLBACK pb_default_field_callback
#define iot_SensorEnvelope_DEFAULT NULL
#define iot_SensorEnvelope_payload_accel_MSGTYPE iot_AccelSample
#define iot_SensorEnvelope_payload_temp_MSGTYPE iot_TempSample

extern const pb_msgdesc_t iot_AccelSample_msg;
extern const pb_msgdesc_t iot_TempSample_msg;
extern const pb_msgdesc_t iot_SensorEnvelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define iot_AccelSample_fields &iot_AccelSample_msg
#define iot_TempSample_fields &iot_TempSample_msg
#define iot_SensorEnvelope_fields &iot_SensorEnvelope_msg

/* Maximum encoded size of messages (where known) */
/* iot_SensorEnvelope_size depends on runtime parameters */
#define IOT_PROTO_SENSORS_PB_H_MAX_SIZE          iot_AccelSample_size
#define iot_AccelSample_size                     21
#define iot_TempSample_size                      11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
