/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "proto/sensors.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(iot_AccelSample, iot_AccelSample, AUTO)


PB_BIND(iot_TempSample, iot_TempSample, AUTO)


PB_BIND(iot_SensorEnvelope, iot_SensorEnvelope, AUTO)



