# Interfaz en la que dnsmasq va a escuchar (la antena Wi-Fi de la Raspberry)
interface=wlan0

# Rango de direcciones IP que se van a asignar a los dispositivos que se conecten
# Formato: IP_inicial, IP_final, Máscara_de_red, Tiempo_de_concesión (lease time)
dhcp-range=192.168.10.10,192.168.10.50,255.255.255.0,24h

# Configurar explícitamente la dirección IP del router (la Raspberry Pi)
dhcp-option=3,192.168.10.1

# No enviar consultas DNS para nombres sin punto o dominio
domain-needed
# No reenviar direcciones IP privadas a servidores DNS externos
bogus-priv
