# Configuración del broker Mosquitto para la Tarea 2

# Puerto en el que escuchará el broker (1883 es el estándar de MQTT sin encriptar)
listener 1883 0.0.0.0

# Permitir conexiones sin usuario ni contraseña
allow_anonymous true

log_dest file /var/log/mosquitto/mosquito.log
log_type subscribe
log_type notice
log_type information
